version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install

  build:
    commands:
      - echo "Compilando proyecto..."
      - mkdir -p dist  # Crea el directorio dist si no existe
      - npm run build   # Ejecuta el build (asegúrate de tener este script en package.json)

  post_build:
    commands:
      - echo "Pipeline ejecutado con éxito en $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: dist