version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install

  build:
    commands:
      - echo "Compilando proyecto..."
      - mkdir -p dist
      # Genera archivos mínimos requeridos para el artefacto
      - echo "Build generado el $(date)" > dist/build-info.txt
      - cp -r src/* dist/ 2>/dev/null || echo "No hay archivos src para copiar"
      - npm run build

  post_build:
    commands:
      - echo "Pipeline ejecutado con éxito en $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: dist