version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install

  build:
    commands:
      - echo "Compilando proyecto..."
      # Genera la carpeta dist (si tu build lo requiere)
      - npm run build  # Ejemplo: Si usas TypeScript o herramientas de bundling

  post_build:
    commands:
      - echo "Pipeline ejecutado con éxito en $(date)"

artifacts:
  files:
    - '**/*'           # Incluir todos los archivos
  base-directory: .    # No usar "dist" (a menos que tu build lo justifique)
  discard-paths: no