version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install

  build:
    commands:
      - echo "Compilando proyecto..."
      - npm run build   # Asegúrate de tener este script en tu package.json

  post_build:
    commands:
      - echo "Pipeline ejecutado con éxito en $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: dist   # Cambia "dist" si tus archivos resultantes están en otra carpeta
